f = open("24_demo.txt")
s = f.readline()
n = len(s)
mx = 1
c = 1
for i in range(n - 1):
    curr = s[i]
    nxt = s[i + 1]
    if curr != nxt:
        c += 1
    else:
        c = 1
    mx = max(c, mx)

print(mx)

# XXXYYXXYZXXYXZYXXXYYXXXXXXXXYZXYXXXYXYZYYZXYXXXXXXXXXYXZXYYXYYYXXXYXYZYYXYXYZXYXXYYXZXXXXYXZXYXYXXXYXXZXXYYZYXXXYYYYZXYYXXZXXXXYXXXYXXXZZXXXZYYZXXZXXXYXXYXXYYXYYXZYXYXZXZYXXYXXXYXXXZYYYYXXXXXZXZXXYXZXZXXZZZYYZXXXXYYZXZYXYYXXZYYXXYXZXXZXXYYXXZXXYYXZXXYXZYXXXXYZXZYXXXYXYYXYXYZYXXXXYXYXXXYXXXXXYYXYXYYXXYZXZYXYXYYZXXXZYXYYYYZYYYZYXXXYYYYYYXZXYYZXZYYXYZZXZXXZYYYYXXXYYXXXXYXZXXYXYXXYYZZZXXYXXXYXYXYXXYZXXYZXXXYXYYXZ
#  |